# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('foto', models.FileField(blank=True, null=True, upload_to='static')),
                ('descricao', tinymce.models.HTMLField(blank=True, null=True)),
                ('data', models.DateField()),
                ('tecnologia', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
