# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170923_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('fim', models.DateField()),
            ],
            options={
                'ordering': ['-fim'],
            },
        ),
    ]
