# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170924_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
