# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_article_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
