# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_work_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
