# Generated by Django 2.0.1 on 2018-02-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20180201_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='media', width_field='image_field'),
        ),
    ]
