# Generated by Django 2.0.1 on 2018-02-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20180201_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_field',
            new_name='image_width',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='media', width_field='image_width'),
        ),
    ]
