# Generated by Django 2.0.1 on 2018-01-24 14:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('tecnology', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=30)),
                ('data', models.DateField()),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
