# Generated by Django 2.0.1 on 2018-01-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tag',
        ),
    ]
