# Generated by Django 2.0.1 on 2018-02-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20180201_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image_width',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='media', width_field='width'),
        ),
    ]
