# Generated by Django 2.0.1 on 2018-01-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('data', models.DateField()),
                ('tag', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
